// Mocks generated by Mockito 5.4.2 from annotations
// in search/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/domain/entities/category.dart' as _i6;
import 'package:core/domain/entities/detail.dart' as _i7;
import 'package:core/domain/repositories/movie_repository.dart' as _i3;
import 'package:core/domain/repositories/tv_show_repository.dart' as _i8;
import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Category>>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Detail>> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Detail>>.value(
            _FakeEither_0<_i5.Failure, _i7.Detail>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Detail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [id],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Category>>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
}

/// A class which mocks [TvShowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowRepository extends _i1.Mock implements _i8.TvShowRepository {
  MockTvShowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>
      getAiringTodayTvShows() => (super.noSuchMethod(
            Invocation.method(
              #getAiringTodayTvShows,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Category>>(
              this,
              Invocation.method(
                #getAiringTodayTvShows,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> getPopularTvShows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvShows,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #getPopularTvShows,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>
      getTopRatedTvShows() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvShows,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Category>>(
              this,
              Invocation.method(
                #getTopRatedTvShows,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Detail>> getTvShowDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvShowDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Detail>>.value(
            _FakeEither_0<_i5.Failure, _i7.Detail>(
          this,
          Invocation.method(
            #getTvShowDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Detail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>
      getTvShowRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvShowRecommendations,
              [id],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Category>>(
              this,
              Invocation.method(
                #getTvShowRecommendations,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>> searchTvShows(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvShows,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Category>>(
          this,
          Invocation.method(
            #searchTvShows,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Category>>>);
}
